### ISSUE TITLE
Make Micro-Videos

### ISSUE THREAD

**Issue by Ma1hT3ach3r** [AYJACKSON-ICS4U/20time-log-due-every-saturday-night-TheCrazyBaconLord#1]
Hi Albert,

Sometimes our imagination makes it difficult to just let us get into a practical gear. If you hold your video to 30 seconds(maybe even 15 seconds)... think commercial length... then you might be able to get more done.

Make sure you leave perfection at the door... perfection is truly nothing... you will find everything in making **Big awful weird** mistakes.

Its a little scary... but you got this!

Can't wait to see anything you make.

Also keep in mind you can make your repo private (if you want) until you are ready to share your videos with the world. 

Have fun and continue to be awesomely creative.

Keep up the good work Albert!

**Comment by ghost** [comment]
Hi Mr. O,

Sorry. I didn't see this issue until like 2 weeks after you opened it, so I didn't reply sooner. I think that 15 to 30 seconds is not enough time for me to include any meaningful messages or information, but I will try to limit how long my videos. Thank you for the advice.

Albert
